# Generated by Django 5.2.1 on 2026-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
