# Generated by Django 5.2.1 on 2026-07-03 12:15

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("finance", "Category")

    default_categories = [
        # Income
        ("Salary", "INCOME"),
        ("Freelancing", "INCOME"),
        ("Business", "INCOME"),
        ("Bonus", "INCOME"),
        ("Investments", "INCOME"),
        ("Interest", "INCOME"),
        ("Gift", "INCOME"),
        ("Other Income", "INCOME"),
        # Expense
        ("Food", "EXPENSE"),
        ("Groceries", "EXPENSE"),
        ("Rent", "EXPENSE"),
        ("Utilities", "EXPENSE"),
        ("Transportation", "EXPENSE"),
        ("Shopping", "EXPENSE"),
        ("Electronics", "EXPENSE"),
        ("Entertainment", "EXPENSE"),
        ("Healthcare", "EXPENSE"),
        ("Education", "EXPENSE"),
        ("Travel", "EXPENSE"),
        ("Insurance", "EXPENSE"),
        ("Bills", "EXPENSE"),
        ("Other Expense", "EXPENSE"),
    ]

    for name, category_type in default_categories:
        Category.objects.get_or_create(
            name=name,
            type=category_type,
            user=None,
            defaults={"is_default": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_category_is_default_alter_category_type_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
